[package]
name = "advent-2020"
version = "0.1.0"
authors = ["flegac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timeit = "0.1.2"
itertools = "0.9.0"
eyre = "0.6"
regex = "1.4.2"
lazy_static = "1.4.0"